TRAIN:
  ENABLE: True
  DATASET: AMD
  BATCH_SIZE: 4
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  EPOCHS: 16
  DEBUG: False
  HPARAM_TUNE: True
DATA:
  PATH_TO_DATA_DIR: /cs/labs/dina/seanco/hadassah/OCT_output/pre_process
  ANNOTATION_PATH: /cs/labs/dina/seanco/hadassah/dl_project/AMD/annotations.csv
  NUM_FRAMES: 96
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  IMG_SIZE: 224
TIMESFORMER:
  ATTENTION_TYPE: space_only
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 5, 12, 19]
  LRS: [1, 0.2, 0.1, 0.01]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: TIMESFORMER_L
  NUM_CLASSES: 2
  ARCH: vit
  LOSS_FUNC: cross_entropy
  LOSS_CLASS_WEIGHT: False
  DROPOUT_RATE: 0.5
  PRETRAINED_PATH: /cs/labs/dina/seanco/hadassah/dl_project/AMD/pretrained/TimeSformer_divST_96x4_224_K400.pyth
  FINETUNE: TRUE
  FINETUNE_PERCENT: 0.9
  NUM_FEATURES_TO_PREDICT: 1
  USE_CHECKPOINT: False
  CHECKPOINT_NAME: VIT_TIMESFORME_L
TEST:
  ENABLE: True
  DATASET: AMD
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
  TEST_OR_VALIDATION: validation
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
  INTERPOLATE_DATA: True
  METHOD: all
  ORDERED: True
  TRANSFORMS: rescale
  MEAN: [ 0.0782, 0.0782, 0.0782 ]
  STD: [ 0.0782, 0.0782, 0.0782 ]
  D_MEAN: [ 0.45, 0.45, 0.45 ]
  D_STD: [ 0.225, 0.225, 0.225 ]
LOSS: AMD_stage
TARGET_FEATURE: AMD_STAGE
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
