TRAIN:
  ENABLE: True
  DATASET: AMD
  BATCH_SIZE: 4
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  EPOCHS: 100
DATA:
  PATH_TO_DATA_DIR: "/media/ron/Seagate Backup #3 Drive AI AMD-T/preprocessed/"
  ANNOTATION_PATH: "/media/ron/Seagate Backup #3 Drive AI AMD-T/labels.csv"
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  IMG_SIZE: 224
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: VIT_8x224_Linear
  NUM_CLASSES: 400
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  PRETRAINED_PATH: "/home/ron/workspace/AMD/TimeSformer/vit_8x224.pyth"
  FINETUNE: TRUE
TEST:
  ENABLE: True
  DATASET: AMD
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
  INTERPOLATE_DATA: False
  METHOD: 8 mid slices
  TRANSFORMS: rescale
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
